// ─────────────────────────────────────────────────────────────────
// BJJ NO-GI · Technique Of The Day — Configuration
// ─────────────────────────────────────────────────────────────────
//
// Each technique entry:
//   id  – sequential natural number (displayed on screen)
//   url – link that opens when the number is clicked
//
// A random technique is picked on every page load.
// ─────────────────────────────────────────────────────────────────

window.TOD_CONFIG = {
  lastUpdate: "2026-07-01",
  techniques: [
    { id:  1, url: "https://www.youtube.com/watch?v=r6mDDpc5474" },
    { id:  2, url: "https://www.youtube.com/shorts/VKxCRh1jODk" },
    { id:  3, url: "https://www.youtube.com/shorts/JfGU1KFeblY" },
    { id:  4, url: "https://www.youtube.com/watch?v=032wIsVv0hY" },
    { id:  5, url: "https://www.youtube.com/shorts/Ht43PYmXaNM" },
    { id:  6, url: "https://www.youtube.com/shorts/xYW7CCmA3ow" },
    { id:  7, url: "https://www.youtube.com/shorts/3UV6nzWwm68" },
    { id:  8, url: "https://www.youtube.com/shorts/r6WcSrPqLaU" },
    { id:  9, url: "https://www.instagram.com/reel/DXIAkv5jPaW/" },
    { id: 10, url: "https://www.instagram.com/p/DXHgdCzgE1x/" },
    { id: 11, url: "https://www.instagram.com/reel/DW6fvitDNIK/" },
    { id: 12, url: "https://www.facebook.com/reel/2022685118662629" },
    { id: 13, url: "https://www.instagram.com/reel/DXDshh3DYwe/" },
    { id: 14, url: "https://www.facebook.com/reel/1709868740030349" },
    { id: 15, url: "https://www.instagram.com/reel/DXAUgW5E8-z/" },
    { id: 16, url: "https://www.instagram.com/reel/DT8BVfrkmBy/" },
    { id: 17, url: "https://www.youtube.com/watch?v=GshEzcqlUbY" },
    { id: 18, url: "https://youtu.be/yPHEGRnRem0" },
    { id: 19, url: "https://www.youtube.com/watch?v=d_zfY7Kjezo" },
    { id: 20, url: "https://www.youtube.com/watch?v=RDrrWZosCMw" },
    { id: 21, url: "https://www.youtube.com/shorts/4O0C267NKt0" },
    { id: 22, url: "https://www.youtube.com/watch?v=tWUkxvM8ppA" },
    { id: 23, url: "https://www.youtube.com/shorts/ztpvgMFYEiw" },
    { id: 24, url: "https://www.youtube.com/watch?v=6bZ5FBXgSm8" },
    { id: 25, url: "https://www.youtube.com/watch?v=rfaaPWZ-ugY" },
    { id: 26, url: "https://www.youtube.com/watch?v=7v_M_ea_7Ik" },
    { id: 27, url: "https://www.instagram.com/p/DXYb0cUCbEE/" },
    { id: 28, url: "https://www.instagram.com/p/CyjEVJeRceY/" },
    { id: 29, url: "https://www.instagram.com/p/CukQ_clJNld/" },
    { id: 30, url: "https://www.instagram.com/reel/DXCLf-gjpud/" },
    { id: 31, url: "https://www.youtube.com/watch?v=pQ43Oy5k9yQ" },
    { id: 32, url: "https://www.youtube.com/watch?v=58ItAArEM4s" },
    { id: 33, url: "https://www.youtube.com/watch?v=qouu5qFtZZA" },
    { id: 34, url: "https://www.youtube.com/watch?v=QwQRDEydJCM" },
    { id: 35, url: "https://www.youtube.com/watch?v=zDl9hklGM-o" },
    { id: 36, url: "https://www.youtube.com/watch?v=xcq2Gqn-cVw" },
    { id: 37, url: "https://www.instagram.com/p/DXeWcy7q5_A/" },
    { id: 38, url: "https://www.facebook.com/reel/1407326453992218" },
    { id: 39, url: "https://www.instagram.com/reel/DXelITLjFT2/" },
    { id: 40, url: "https://www.instagram.com/reel/DWoRQX_qA7C/" },
    { id: 41, url: "https://www.facebook.com/reel/1522172702920090" },
    { id: 42, url: "https://www.facebook.com/reel/1307997081296257" },
    { id: 43, url: "https://www.instagram.com/reel/DY5saZQtZUl/" },
    { id: 44, url: "https://www.youtube.com/watch?v=3x7Mgxcy3Wo" },
    { id: 45, url: "https://www.youtube.com/watch?v=i_zvYu5w92g" },
    { id: 46, url: "https://www.facebook.com/reel/1968124170731436" },
    { id: 47, url: "https://www.facebook.com/reel/1382686100368051" },
    { id: 48, url: "https://www.facebook.com/reel/27101855196109607" },
    { id: 49, url: "https://www.facebook.com/reel/879672428483462" },
    { id: 50, url: "https://www.facebook.com/reel/1730091534840778" },
    { id: 51, url: "https://www.instagram.com/reel/DZH9ZwoBk6d/" },
    { id: 52, url: "https://www.instagram.com/reel/DZVHREBuB8O/" },
    { id: 53, url: "https://www.instagram.com/reel/DZU_T5BOLKV/" },
    { id: 54, url: "https://www.instagram.com/reel/DZTVXxTviqO/" },
    { id: 55, url: "https://www.facebook.com/reel/1033702495978983" },
    { id: 56, url: "https://www.facebook.com/reel/3549756735171878" },
    { id: 57, url: "https://www.facebook.com/reel/2832153300288197" },
    { id: 58, url: "https://www.facebook.com/reel/1352782366761232" },
    { id: 59, url: "https://www.facebook.com/reel/2247518902661105" },
    { id: 60, url: "https://www.facebook.com/reel/1659815638568530" },
    { id: 61, url: "https://www.facebook.com/reel/1516580563495043" },
    { id: 62, url: "https://www.instagram.com/reel/DZFuanvAQnq/" },
    { id: 63, url: "https://www.instagram.com/reel/DZAXOWXhfAy/" },
    { id: 64, url: "https://www.instagram.com/reel/DYsW3tUMbOH/" },
    { id: 65, url: "https://www.instagram.com/reel/DYplef3Rdz3/" },
    { id: 66, url: "https://www.facebook.com/reel/2075481040041198" },
    { id: 67, url: "https://www.instagram.com/reel/DYu5oVfs6Uf/" },
    { id: 68, url: "https://www.instagram.com/reel/DY9zdcqJ-n7/" },
    { id: 69, url: "https://www.instagram.com/reel/DYZ6tqzIO_s/" },
    { id: 70, url: "https://www.facebook.com/reel/1728489001919180" },
    { id: 71, url: "https://www.facebook.com/reel/1527732142363056" },
    { id: 72, url: "https://www.instagram.com/reel/DYOFrOqOQsx/" },
    { id: 73, url: "https://www.instagram.com/reel/DY6JlktRUak/" },
    { id: 74, url: "https://www.instagram.com/reel/DY42LT7uDy1/" },
    { id: 75, url: "https://www.facebook.com/reel/2073238036562898" },
    { id: 76, url: "https://www.facebook.com/reel/1675847000103233" },
    { id: 77, url: "https://www.instagram.com/reel/DY2DMMtxAJm/" },
    { id: 78, url: "https://www.facebook.com/reel/1478604637297027" },
    { id: 79, url: "https://www.facebook.com/reel/994630306750682" },
    { id: 80, url: "https://www.instagram.com/p/DYrMwsvDFdg/" },
    { id: 81, url: "https://www.instagram.com/reel/DTQG87iDWgn/" },
    { id: 82, url: "https://www.instagram.com/reel/DYzb6NMNTU0/" },
    { id: 83, url: "https://www.instagram.com/p/DZHTczeqv-C/" },
    { id: 84, url: "https://www.instagram.com/p/DZAZoS9OtdJ/" },
    { id: 85, url: "https://www.instagram.com/p/DYuw2bLhgw-/" },
    { id: 86, url: "https://www.instagram.com/p/DYSQG76hjuR/" },
    { id: 87, url: "https://www.instagram.com/p/DX3fJdORsuc/" },
    { id: 88, url: "https://www.instagram.com/p/DXw2Uc2DL-t/" },
    { id: 89, url: "https://www.instagram.com/p/DWwryjXEfnD/" },
    { id: 90, url: "https://www.instagram.com/p/DUmEqUkifjh/" },
    { id:  91, url: "https://www.youtube.com/watch?v=_5hYXnghxDE" },
    { id:  92, url: "https://www.youtube.com/watch?v=-LhSBH3BBFE" },
    { id:  93, url: "https://www.youtube.com/watch?v=-z_UYv5w_Qk" },
    { id:  94, url: "https://www.youtube.com/watch?v=2l7kndNwo-c" },
    { id:  95, url: "https://www.youtube.com/watch?v=37dCDlxk4Eo" },
    { id:  96, url: "https://www.youtube.com/watch?v=4DHzLvLd-0Y" },
    { id:  97, url: "https://www.youtube.com/watch?v=4H7H5P2TBfY" },
    { id:  98, url: "https://www.youtube.com/watch?v=4WqkHFi7ac0" },
    { id:  99, url: "https://www.youtube.com/watch?v=4WxiXQucLPE" },
    { id: 100, url: "https://www.youtube.com/watch?v=5A8F-39BUIk" },
    { id: 101, url: "https://www.youtube.com/watch?v=61unSJ7vu4I" },
    { id: 102, url: "https://www.youtube.com/watch?v=6g67pwVcK6U" },
    { id: 103, url: "https://www.youtube.com/watch?v=7igJLHdcg1I" },
    { id: 104, url: "https://www.youtube.com/watch?v=8sWY83SsbLk" },
    { id: 105, url: "https://www.youtube.com/watch?v=8uaFGdlYwOw" },
    { id: 106, url: "https://www.youtube.com/watch?v=9UWgyOO8Sjg" },
    { id: 107, url: "https://www.youtube.com/watch?v=ADyFc4WMzbQ" },
    { id: 108, url: "https://www.youtube.com/watch?v=aGNHoMZiP1k" },
    { id: 109, url: "https://www.youtube.com/watch?v=BfeJsup9xz8" },
    { id: 110, url: "https://www.youtube.com/watch?v=bXhGj3ssCTk" },
    { id: 111, url: "https://www.youtube.com/watch?v=c3hDx2mYTcQ" },
    { id: 112, url: "https://www.youtube.com/watch?v=CxYwm1ufjJo" },
    { id: 113, url: "https://www.youtube.com/watch?v=cz3VTLi0Nfw" },
    { id: 114, url: "https://www.youtube.com/watch?v=dhZgpDHCARw" },
    { id: 115, url: "https://www.youtube.com/watch?v=dl_SvwPfpDc" },
    { id: 116, url: "https://www.youtube.com/watch?v=eDiCSF_lZP0" },
    { id: 117, url: "https://www.youtube.com/watch?v=eNilli4yUN8" },
    { id: 118, url: "https://www.youtube.com/watch?v=ETtj0vrorBk" },
    { id: 119, url: "https://www.youtube.com/watch?v=EULMFdfiUak" },
    { id: 120, url: "https://www.youtube.com/watch?v=fJ4WGwF_q-Q" },
    { id: 121, url: "https://www.youtube.com/watch?v=h4KlGNvZaKg" },
    { id: 122, url: "https://www.youtube.com/watch?v=IEJTtbstxIY" },
    { id: 123, url: "https://www.youtube.com/watch?v=J8QJ3tOEBsY" },
    { id: 124, url: "https://www.youtube.com/watch?v=JLcUHuHE05w" },
    { id: 125, url: "https://www.youtube.com/watch?v=JX0HL0WpYPs" },
    { id: 126, url: "https://www.youtube.com/watch?v=Kf_ptXBDsKE" },
    { id: 127, url: "https://www.youtube.com/watch?v=KIAIT36M72o" },
    { id: 128, url: "https://www.youtube.com/watch?v=klxuT9teD9o" },
    { id: 129, url: "https://www.youtube.com/watch?v=L1HoQPBGV10" },
    { id: 130, url: "https://www.youtube.com/watch?v=L3gkpR4w8cM" },
    { id: 131, url: "https://www.youtube.com/watch?v=l45ZVIfplg0" },
    { id: 132, url: "https://www.youtube.com/watch?v=lj985a5UJl0" },
    { id: 133, url: "https://www.youtube.com/watch?v=lpUImmq-9jU" },
    { id: 134, url: "https://www.youtube.com/watch?v=lWv_jyFdpxU" },
    { id: 135, url: "https://www.youtube.com/watch?v=mycu_0dRZg8" },
    { id: 136, url: "https://www.youtube.com/watch?v=oxxMfJSSAXg" },
    { id: 137, url: "https://www.youtube.com/watch?v=QBRp7pnpi9Q" },
    { id: 138, url: "https://www.youtube.com/watch?v=qHBGJqN-eSE" },
    { id: 139, url: "https://www.youtube.com/watch?v=R0AlwoWcXHA" },
    { id: 140, url: "https://www.youtube.com/watch?v=rhvfZc27erE" },
    { id: 141, url: "https://www.youtube.com/watch?v=RscLPT0F-DE" },
    { id: 142, url: "https://www.youtube.com/watch?v=s3Mm2PcqwpE" },
    { id: 143, url: "https://www.youtube.com/watch?v=SfYrG7CJAZE" },
    { id: 144, url: "https://www.youtube.com/watch?v=sViKOV2epJI" },
    { id: 145, url: "https://www.youtube.com/watch?v=v68TUDCHSe8" },
    { id: 146, url: "https://www.youtube.com/watch?v=VLvB2DjqWkk" },
    { id: 147, url: "https://www.youtube.com/watch?v=WxCZtFecwo0" },
    { id: 148, url: "https://www.youtube.com/watch?v=x1Jsf4gplv4" },
    { id: 149, url: "https://www.youtube.com/watch?v=xKKV8u1XDus" },
    { id: 150, url: "https://www.youtube.com/watch?v=XY-6ish13Sc" },
    { id: 151, url: "https://www.youtube.com/watch?v=YHHMEF-Up4k" },
    { id: 152, url: "https://www.youtube.com/watch?v=YoNtE7EDNKI" },
    { id: 153, url: "https://www.youtube.com/watch?v=Ys4bk7CF-LU" },
    { id: 154, url: "https://www.youtube.com/watch?v=YWrgo-jZmC8" },
    { id: 155, url: "https://www.youtube.com/watch?v=ZPNJ3kWLTqo" },
    { id: 156, url: "https://www.youtube.com/watch?v=Zy2HZcdsdOg" }, 
    { id: 157, url: "https://www.youtube.com/watch?v=GCN0zvbMuqU" }, 
    { id: 158, url: "https://www.instagram.com/reels/DZaAFhAhDoB/" }, 
    { id: 159, url: "https://www.facebook.com/watch/?v=36239234465692040" },
    { id: 160, url: "https://www.facebook.com/reel/2123683081884545" }, 
    { id: 161, url: "https://www.facebook.com/reel/1664007091284454" },
    { id: 162, url: "https://www.facebook.com/reel/2069149276977041" },
    { id: 163, url: "https://www.facebook.com/reel/724872520687896" },
    { id: 164, url: "https://www.facebook.com/reel/1311515144167256" }, 
    // Snap down for BJJ (Lachlan Giles)
    { id: 165, url: "https://www.youtube.com/watch?v=BjvWqnaC5AI" }, 
    // body lock
    { id: 166, url: "https://www.youtube.com/watch?v=r-FNcolHsg4" },
    { id: 167, url: "https://www.youtube.com/watch?v=we3wrU-Ctbw" },
    { id: 168, url: "https://www.youtube.com/watch?v=spB8qALp5rA" },
    { id: 169, url: "https://www.youtube.com/watch?v=ce7g__eV5iA" },
    { id: 170, url: "https://www.youtube.com/watch?v=mk-kJx2yLYY" },
    // side control frame building
    { id: 171, url: "https://www.youtube.com/watch?v=N6yWdr2kJRI" },
    { id: 172, url: "https://www.youtube.com/watch?v=2rFuFFverLg" },
    // headquaters
    { id: 173, url: "https://www.youtube.com/watch?v=quM3u9Jxthg" },
    { id: 174, url: "https://www.youtube.com/watch?v=z3-Yb08-VhQ" },
    { id: 175, url: "https://www.youtube.com/watch?v=WFaBuxpRM7U" },
    { id: 176, url: "https://www.youtube.com/watch?v=BgcSkD9-YUU" },
    { id: 177, url: "https://www.youtube.com/watch?v=YjNkzpX9_DI" },
    { id: 178, url: "https://www.youtube.com/watch?v=3x7Mgxcy3Wo" },
    { id: 179, url: "https://www.youtube.com/watch?v=pMmyD-sD7oM" },
    { id: 180, url: "https://www.youtube.com/watch?v=GSq-dig3Ag8" },
    { id: 181, url: "https://www.youtube.com/watch?v=OdscGUlottI" },
    // leg drag
    { id: 182, url: "https://www.youtube.com/shorts/xjm2WoMfBq8" },
    { id: 183, url: "https://www.youtube.com/shorts/wvjReqf-SpM" },
    { id: 184, url: "https://www.youtube.com/watch?v=ZyNXERJtwDc" },
    { id: 185, url: "https://www.youtube.com/watch?v=7II5bP00TsQ" },
    { id: 186, url: "https://www.youtube.com/shorts/46reRe4-iKQ" },
    { id: 187, url: "https://www.youtube.com/watch?v=xVIuZaJTb1o" },
    { id: 188, url: "https://www.youtube.com/watch?v=4c-v1OEPukc" },
    { id: 189, url: "https://www.youtube.com/watch?v=djOPJWmQmT0" },
    { id: 190, url: "https://www.youtube.com/watch?v=MTPxvLfW_co" },
    { id: 191, url: "https://www.youtube.com/watch?v=q6h73eHd2YM" },
    // float passing
    { id: 192, url: "https://www.youtube.com/watch?v=wbkhWZk6o-U" },
    { id: 193, url: "https://www.youtube.com/watch?v=6g67pwVcK6U" },
    { id: 194, url: "https://www.youtube.com/watch?v=X3gjk5iQx3Q" },
    { id: 195, url: "https://www.youtube.com/watch?v=iahli8rEm6c" },
    // ---
    { id: 196, url: "https://www.youtube.com/watch?v=i9rA2rDb05k" }
  ]
};
