// ─────────────────────────────────────────────────────────────────
// BJJ NO-GI · Technique Of The Day — Configuration
// ─────────────────────────────────────────────────────────────────
//
// Each technique entry:
//   id  – sequential natural number (displayed on screen)
//   url – link that opens when the number is clicked
//
// A random technique is picked on every page load.
// ─────────────────────────────────────────────────────────────────

window.TOD_CONFIG = {
  techniques: [
    { id:  1, url: "https://www.youtube.com/watch?v=r6mDDpc5474" },
    { id:  2, url: "https://www.youtube.com/shorts/VKxCRh1jODk" },
    { id:  3, url: "https://www.youtube.com/shorts/JfGU1KFeblY" },
    { id:  4, url: "https://www.youtube.com/watch?v=032wIsVv0hY" },
    { id:  5, url: "https://www.youtube.com/shorts/Ht43PYmXaNM" },
    { id:  6, url: "https://www.youtube.com/shorts/xYW7CCmA3ow" },
    { id:  7, url: "https://www.youtube.com/shorts/3UV6nzWwm68" },
    { id:  8, url: "https://www.youtube.com/shorts/r6WcSrPqLaU" },
    { id:  9, url: "https://www.instagram.com/reel/DXIAkv5jPaW/" },
    { id: 10, url: "https://www.instagram.com/p/DXHgdCzgE1x/" },
    { id: 11, url: "https://www.instagram.com/reel/DW6fvitDNIK/" },
    { id: 12, url: "https://www.facebook.com/reel/2022685118662629" },
    { id: 13, url: "https://www.instagram.com/reel/DXDshh3DYwe/" },
    { id: 14, url: "https://www.facebook.com/reel/1709868740030349" },
    { id: 15, url: "https://www.instagram.com/reel/DXAUgW5E8-z/" },
    { id: 16, url: "https://www.instagram.com/reel/DT8BVfrkmBy/" },
    { id: 17, url: "https://www.youtube.com/watch?v=GshEzcqlUbY" },
    { id: 18, url: "https://youtu.be/yPHEGRnRem0" },
    { id: 19, url: "https://www.youtube.com/watch?v=d_zfY7Kjezo" },
    { id: 20, url: "https://www.youtube.com/watch?v=RDrrWZosCMw" },
    { id: 21, url: "https://www.youtube.com/shorts/4O0C267NKt0" },
    { id: 22, url: "https://www.youtube.com/watch?v=tWUkxvM8ppA" },
    { id: 23, url: "https://www.youtube.com/shorts/ztpvgMFYEiw" },
    { id: 24, url: "https://www.youtube.com/watch?v=6bZ5FBXgSm8" },
    { id: 25, url: "https://www.youtube.com/watch?v=rfaaPWZ-ugY" },
    { id: 26, url: "https://www.youtube.com/watch?v=7v_M_ea_7Ik" },
    { id: 27, url: "https://www.instagram.com/p/DXYb0cUCbEE/" },
    { id: 28, url: "https://www.instagram.com/p/CyjEVJeRceY/" },
    { id: 29, url: "https://www.instagram.com/p/CukQ_clJNld/" },
    { id: 30, url: "https://www.instagram.com/reel/DXCLf-gjpud/" },
    { id: 31, url: "https://www.youtube.com/watch?v=pQ43Oy5k9yQ" },
    { id: 32, url: "https://www.youtube.com/watch?v=58ItAArEM4s" },
    { id: 33, url: "https://www.youtube.com/watch?v=qouu5qFtZZA" },
    { id: 34, url: "https://www.youtube.com/watch?v=QwQRDEydJCM" },
    { id: 35, url: "https://www.youtube.com/watch?v=zDl9hklGM-o" },
    { id: 36, url: "https://www.youtube.com/watch?v=xcq2Gqn-cVw" },
    { id: 37, url: "https://www.instagram.com/p/DXeWcy7q5_A/" },
    { id: 38, url: "https://www.facebook.com/reel/1407326453992218" },
    { id: 39, url: "https://www.instagram.com/reel/DXelITLjFT2/" },
    { id: 40, url: "https://www.instagram.com/reel/DWoRQX_qA7C/" },
    { id: 41, url: "https://www.facebook.com/reel/1522172702920090" },
    { id: 42, url: "https://www.facebook.com/reel/1307997081296257" },
    { id: 43, url: "https://www.instagram.com/reel/DY5saZQtZUl/" },
    { id: 44, url: "https://www.youtube.com/watch?v=3x7Mgxcy3Wo" },
    { id: 45, url: "https://www.youtube.com/watch?v=i_zvYu5w92g" },
    { id: 46, url: "https://www.facebook.com/reel/1968124170731436" },
    { id: 47, url: "https://www.facebook.com/reel/1382686100368051" },
    { id: 48, url: "https://www.facebook.com/reel/27101855196109607" },
    { id: 49, url: "https://www.facebook.com/reel/879672428483462" },
    { id: 50, url: "https://www.facebook.com/reel/1730091534840778" },
    { id: 51, url: "https://www.instagram.com/reel/DZH9ZwoBk6d/" },
    { id: 52, url: "https://www.instagram.com/reel/DZVHREBuB8O/" },
    { id: 53, url: "https://www.instagram.com/reel/DZU_T5BOLKV/" },
    { id: 54, url: "https://www.instagram.com/reel/DZTVXxTviqO/" },
    { id: 55, url: "https://www.facebook.com/reel/1033702495978983" },
    { id: 56, url: "https://www.facebook.com/reel/3549756735171878" },
    { id: 57, url: "https://www.facebook.com/reel/2832153300288197" },
    { id: 58, url: "https://www.facebook.com/reel/1352782366761232" },
    { id: 59, url: "https://www.facebook.com/reel/2247518902661105" },
    { id: 60, url: "https://www.facebook.com/reel/1659815638568530" },
    { id: 61, url: "https://www.facebook.com/reel/1516580563495043" },
    { id: 62, url: "https://www.instagram.com/reel/DZFuanvAQnq/" },
    { id: 63, url: "https://www.instagram.com/reel/DZAXOWXhfAy/" },
    { id: 64, url: "https://www.instagram.com/reel/DYsW3tUMbOH/" },
    { id: 65, url: "https://www.instagram.com/reel/DYplef3Rdz3/" },
    { id: 66, url: "https://www.facebook.com/reel/2075481040041198" },
    { id: 67, url: "https://www.instagram.com/reel/DYu5oVfs6Uf/" },
    { id: 68, url: "https://www.instagram.com/reel/DY9zdcqJ-n7/" },
    { id: 69, url: "https://www.instagram.com/reel/DYZ6tqzIO_s/" },
    { id: 70, url: "https://www.facebook.com/reel/1728489001919180" },
    { id: 71, url: "https://www.facebook.com/reel/1527732142363056" },
    { id: 72, url: "https://www.instagram.com/reel/DYOFrOqOQsx/" },
    { id: 73, url: "https://www.instagram.com/reel/DY6JlktRUak/" },
    { id: 74, url: "https://www.instagram.com/reel/DY42LT7uDy1/" },
    { id: 75, url: "https://www.facebook.com/reel/2073238036562898" },
    { id: 76, url: "https://www.facebook.com/reel/1675847000103233" },
    { id: 77, url: "https://www.instagram.com/reel/DY2DMMtxAJm/" },
    { id: 78, url: "https://www.facebook.com/reel/1478604637297027" },
    { id: 79, url: "https://www.facebook.com/reel/994630306750682" },
    { id: 80, url: "https://www.instagram.com/p/DYrMwsvDFdg/" },
    { id: 81, url: "https://www.instagram.com/reel/DTQG87iDWgn/" },
    { id: 82, url: "https://www.instagram.com/reel/DYzb6NMNTU0/" },
    { id: 83, url: "https://www.instagram.com/p/DZHTczeqv-C/" },
    { id: 84, url: "https://www.instagram.com/p/DZAZoS9OtdJ/" },
    { id: 85, url: "https://www.instagram.com/p/DYuw2bLhgw-/" },
    { id: 86, url: "https://www.instagram.com/p/DYSQG76hjuR/" },
    { id: 87, url: "https://www.instagram.com/p/DX3fJdORsuc/" },
    { id: 88, url: "https://www.instagram.com/p/DXw2Uc2DL-t/" },
    { id: 89, url: "https://www.instagram.com/p/DWwryjXEfnD/" },
    { id: 90, url: "https://www.instagram.com/p/DUmEqUkifjh/" }
  ]
};
